### PR TITLE
Plugins should be git submodules not separate repositories

### PR DESCRIPTION
**Pull request by mcepl**
Or at least there should be an alternative for those of us who have configuration files in the git repository already.

### CODE REVIEW

**Comment by erf** [comment]
Hi, i don't have much experience with git submodules, except some headache using them some time back, so i would like to avoid them if possible.. Could you elaborate why you'd like to add plugins as submodules and what advantages that entails? Would you add them as submodules to `vis` or `vis-plug`? 

Regarding an "alternative to existing config files", you could copy `vis-plug` to your config repo ( or make an install script ), and setup your `visrc.lua` config with other plugins you need. And call `plug-install` once. Could you explain what limits your use now?

**Comment by mcepl** [comment]
> Hi, i don't have much experience with git submodules, except some headache using them some time back, so i would like to avoid them if possible.. Could you elaborate why you'd like to add plugins as submodules and what advantages that entails? Would you add them as submodules to `vis` or `vis-plug`?

Repo with submodules is easier to share between two computers than repo with included git independent repositories. It just doesn't work well.

The structure I have is

* Directory ``~/.config/dotfiles`` is the main git repo.

* That includes ``~/.config/dotfiles/vis`` as a simple subdirectory (symlinked to ``~/.config/vis``)

* That includes ``~/.config/dotfiles/vis/plugins`` with vis plugins as submodules:

```sh
dotfiles@stitny (master)$ git submodule 
 1f741cd83df09fbd0698d3354e7411f87965757b dircolors (heads/master)
 c31ee308c67d837bc2be8c1cca17c34792372dbb emacs.d/packages/emacs-vim-modeline (heads/master)
 cabf68cb822b3bc01102452dcd6b3e881bcd6402 vis/plugins/vis-commentary (heads/master)
 a1f5f67e1de0884151919ec3e5ea8e3f24395df7 vis/plugins/vis-cursors (heads/master)
 94bdf52d646ad0b5dc88baa029fc834f553d5b0e vis/plugins/vis-editorconfig (heads/pr/4)
 ef104ea956776a97d1a5ff07281606eb0ab9e7fe vis/plugins/vis-fzf-open (heads/master)
 2f21a4508ef8df8a20a26e20d962e103c763710f vis/plugins/vis-plug (heads/submodules)
dotfiles@stitny (master)$
```

This whole thing is much easier to maintain and share between two computers.

**Comment by erf** [comment]
Your change is based on that `VIS_PATH` in your case `~/.config/dotfiles/vis`, is a git repo, this is not always the case ( not in my case ). Also in your example is `git-plug` a submodule? That need to be installed first for the other commands to work. Also not sure the `plug-update` command would work in after this update? So all in all, i'm not sure about this PR, since it does not just work out of the box. I think you have found a system that works for you, and maybe you dont need this plugin? Also maybe this plugin is not needed at all, if you just have a good way to configure your dotfiles. But if you have some good suggestions on how to make this work, im happy to hear them.

**Comment by mcepl** [comment]
You are right. This system works just for me. Yes, I need this plugin for ``.init()`` method, but I have problems to make ``plug-install`` work correctly. And yes, ``git pull`` works even inside of submodules.

**Pull request closed without merging**
